
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: lambda-probot-express

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

functions:

  router:
    handler: handler.router

    environment:
      WEBHOOK_SECRET: development
      APP_ID: 0000
      SENTRY_DSN: https://<user>:<key>@sentry.io/0000

    events:
      - http:
         path: "{page+}"
         method: get
      - http:
         path: /
         method: get
      - http:
         path: /
         method: post
